### ISSUE TITLE
error when trying to import

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/examples#23]
```
$ python import_video.py   --regex ".*/(?P<camera>\w+?)\-(?P<epoch>\d+)\.mp4"   --hook_data_json_file /tmp/hook_data.json   "~/input_videos"   "~/Documents/workspace/prod/examples/batch_import/camio_hooks.py"   "192.168.1.49" -v
INFO:root:submitted hooks module: '~/Documents/workspace/prod/examples/batch_import/camio_hooks.py'
Traceback (most recent call last):
  File "import_video.py", line 332, in <module>
    main()
  File "import_video.py", line 324, in main
    job_id = GenericImporter().run()
  File "import_video.py", line 287, in run
    self.init_args()
  File "import_video.py", line 261, in init_args
    self.module = imp.load_source('hooks_module', self.args.hook_module)
IOError: [Errno 2] No such file or directory
```

**Comment by jcmaslan** [comment]
removing the quotes around input directory and module fixed, so this worked:
```
python import_video.py   --regex ".*/(?P<camera>\w+?)\-(?P<epoch>\d+)\.mp4"   --hook_data_json_file /tmp/hook_data.json   ~/input_videos   ~/Documents/workspace/prod/examples/batch_import/camio_hooks.py   "192.168.1.49"
```
